// tslint:disable
/**
 * Good Bad Reviews
 * Good Bad Reviews
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime";
/**
 *
 * @export
 * @interface Review
 */
export interface Review {
  /**
   *
   * @type {string}
   * @memberof Review
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Review
   */
  productName: string;
}

export function ReviewFromJSON(json: any): Review {
  return {
    id: json["id"],
    productName: json["productName"]
  };
}

export function ReviewToJSON(value?: Review): any {
  if (value === undefined) {
    return undefined;
  }
  return {
    id: value.id,
    productName: value.productName
  };
}
