// tslint:disable
/**
 * Good Bad Reviews
 * Good Bad Reviews
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime";
/**
 *
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
  /**
   *
   * @type {string}
   * @memberof ValidationError
   */
  error: string;
  /**
   *
   * @type {string}
   * @memberof ValidationError
   */
  message: string;
  /**
   *
   * @type {number}
   * @memberof ValidationError
   */
  statusCode: number;
}

export function ValidationErrorFromJSON(json: any): ValidationError {
  return {
    error: json["error"],
    message: json["message"],
    statusCode: json["statusCode"]
  };
}

export function ValidationErrorToJSON(value?: ValidationError): any {
  if (value === undefined) {
    return undefined;
  }
  return {
    error: value.error,
    message: value.message,
    statusCode: value.statusCode
  };
}
