openapi: 3.0.0
info:
  title: Good Bad Reviews
  description: Good Bad Reviews
  version: 0.0.0
servers:
  - url: https://localhost:3000/
paths:
  /reviews:
    get:
      summary: List reviews
      operationId: listReviews
      tags: [Review]
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Review"

    post:
      summary: Create review
      operationId: createReview
      tags: [Review]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReviewParams"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Review"
        "400":
          description: "Invalid request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"

components:
  schemas:
    ReviewParams:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 3

    Review:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string

    ValidationError:
      type: object
      required:
        - error
        - message
        - statusCode
      properties:
        error:
          type: string
        message:
          type: string
        statusCode:
          type: number
